# Question-1

In [2]:
import numpy as np

arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question-2

In [4]:
import numpy as np

a1=[]
a2=[]

print("list1:")
for i in range(0,5):
    i=int(input())
    a1.append(i)

print("list2:")
for j in range(0,5):
    j=int(input())
    a2.append(j)

arr1=np.array(a1)
arr2=np.array(a2)

con=np.concatenate((arr1,arr2),axis=0)
print("concatenated list:")
print(con)

s=np.sort(con)
print("sorted list:")
print(s)

list1:
1
2
3
4
5
list2:
6
7
8
9
0
concatenated list:
[1 2 3 4 5 6 7 8 9 0]
sorted list:
[0 1 2 3 4 5 6 7 8 9]


# Question-3

In [5]:
import numpy as np

arr = np.arange(6).reshape(2,3)
print(arr)
print("No. of dimensions: ", arr.ndim)
print("size of the array: ", arr.size)

[[0 1 2]
 [3 4 5]]
No. of dimensions:  2
size of the array:  6


# Question-4

In [6]:
#using newaxis()
arr = np.arange(6)
a = arr[np.newaxis, :]
print(a.shape) 

#using expand_dims()
b = np.expand_dims(arr, axis=1)
print(b.shape)

(1, 6)
(6, 1)


# Question-5

In [7]:
import numpy as np

a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

ver=np.vstack((a1,a2))
hor=np.hstack((a1,a2))
print("vertical stack:\n",ver)
print("horizontal stack:\n",hor)

vertical stack:
 [[1 1]
 [2 2]
 [3 3]
 [4 4]]
horizontal stack:
 [[1 1 3 3]
 [2 2 4 4]]


# Question-6

In [8]:
import numpy as np

arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 10, 11, 13, 18, 14, 19, 20])
unique_values = np.unique(arr)
print("unique values:\n",unique_values)
#count=np.count
unique_values, occurrence_count = np.unique(arr, return_counts=True)
print("count of unique values:\n",occurrence_count)

unique values:
 [10 11 12 13 14 15 16 17 18 19 20]
count of unique values:
 [1 3 1 2 2 1 1 1 1 1 1]
